'FACEBOOK_KEY': "671441556266904"
'FACEBOOK_SECRET': "c8a0b1ef8f8db6ccd713089424e71b15"
'S3_BUCKET_NAME': "medibolt"
"AWS_ACCESS_KEY_ID": "AKIAITRSCMNFAUY6TKPQ"
"AWS_SECRET_ACCESS_KEY": "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"